spring.application.name=payment-service

# Server Port for Payment Service
server.port=8082

# Database Connection Settings (Connecting to port 5433 and payment_db)
spring.datasource.url=jdbc:postgresql://localhost:5433/payment_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
# Shows the actual SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

